### ISSUE TITLE
Define RDDL-Validator Monikers

### ISSUE THREAD

**Issue by eckelj** [rddl-network/node_maintenance#1]
The moniker of each validator has to be defined accordingly. 
All of them are equal at this point, and it is impossible to differentiate them on the network explorer easily.

**Comment by eckelj** [comment]
@jmastr I set the moniker of all the validators. Can you set the moniker of the node being exposed to the explorer rpc.rddl.io, so that it appears as such in the explorer?
![Screenshot from 2023-03-21 18-11-55](https://user-images.githubusercontent.com/1703752/226688558-d3632a15-56e8-4f8b-9be5-d3beff0a9673.png)

I suggest the name RDDL-Explorer-Node

**Comment by eckelj** [comment]
@jmastr the moniker is an entry in the ./tendermint/config/config.toml configuration file

**Comment by jmastr** [comment]
@eckelj It is defined here: https://github.com/rddl-network/tendermint-explorer/blob/2a5baa6babacbbc5a7a758582d5d0083cf4f5e37/chart/values.yaml#L159

What do you want it to be?

**Comment by jmastr** [comment]
https://github.com/rddl-network/tendermint-explorer/pull/23
